# Generated by Django 3.0.6 on 2020-05-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys_app', '0001_initial'),
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
    ]
