# Generated by Django 3.0.6 on 2020-05-13 01:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, unique=True, verbose_name='Подразделение')),
                ('head_of_department', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True)),
                ('workers', models.PositiveIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ManyToManyField(to='companies_app.Company')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies_app.Structure')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
    ]
