# Generated by Django 3.0.6 on 2020-05-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
