# Generated by Django 3.0.6 on 2020-05-11 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies_app', '0003_remove_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
