# Generated by Django 3.0.6 on 2020-05-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_company_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employee',
            new_name='employees',
        ),
    ]
