# Generated by Django 3.0.6 on 2020-06-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='level',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tree_id',
        ),
    ]
