# Generated by Django 3.0.6 on 2020-06-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returncode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Pages'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='surveys_app.Question'),
        ),
        migrations.AddField(
            model_name='polyresponse',
            name='answer',
            field=models.ManyToManyField(blank=True, to='surveys_app.Answer'),
        ),
        migrations.AddField(
            model_name='polyresponse',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Question'),
        ),
        migrations.AddField(
            model_name='polyresponse',
            name='survey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
        migrations.AddField(
            model_name='pages',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
        migrations.AddField(
            model_name='monoresponse',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Answer'),
        ),
        migrations.AddField(
            model_name='monoresponse',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Question'),
        ),
        migrations.AddField(
            model_name='monoresponse',
            name='survey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Question'),
        ),
    ]
