# Generated by Django 3.0.6 on 2020-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='bye_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Завешение'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='hello_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Приветствие'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='info_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Инструкция'),
        ),
    ]
