# Generated by Django 3.0.6 on 2020-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_auto_20200614_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
