# Generated by Django 3.0.6 on 2020-06-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_auto_20200612_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='OfferedAnswer',
        ),
    ]
