# Generated by Django 3.0.6 on 2020-05-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_auto_20200524_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='language',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Language'),
        ),
    ]
