# Generated by Django 3.0.6 on 2020-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_auto_20200613_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Mono Choice', 'Mono Choice'), ('Poly Choice', 'Poly Choice')], default='Mono Choice', max_length=255),
        ),
    ]
