# Generated by Django 3.0.6 on 2020-06-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0003_auto_20200612_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredanswer',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='offeredanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Question'),
            preserve_default=False,
        ),
    ]
