# Generated by Django 3.0.6 on 2020-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0003_auto_20200613_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Mono', 'Mono'), ('Poly', 'Poly'), ('Text', 'Text')], default='Mono', max_length=255),
        ),
    ]
