# Generated by Django 3.0.6 on 2020-06-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0003_auto_20200614_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.UserCode'),
        ),
    ]
