# Generated by Django 3.0.6 on 2020-05-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_company_employees'),
        ('surveys_app', '0003_statustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(blank=True, max_length=128, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ManyToManyField(blank=True, to='companies_app.Company')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.StatusType')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
    ]
