# Generated by Django 3.0.6 on 2020-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0004_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
