# Generated by Django 3.0.6 on 2020-05-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0004_auto_20200528_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='date_created',
        ),
    ]
