# Generated by Django 3.0.6 on 2020-05-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0005_survey_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
