# Generated by Django 3.0.6 on 2020-05-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0005_remove_survey_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
