# Generated by Django 3.0.6 on 2020-05-31 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0006_survey_created_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_day',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 0, 27, 12, 735210, tzinfo=utc)),
        ),
    ]
