# Generated by Django 3.0.6 on 2020-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0006_auto_20200613_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='link',
        ),
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
