# Generated by Django 3.0.6 on 2020-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0006_auto_20200513_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
