# Generated by Django 3.0.6 on 2020-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0007_auto_20200613_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(blank=True, to='surveys_app.Question'),
        ),
    ]
