# Generated by Django 3.0.6 on 2020-05-31 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0007_auto_20200531_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
