# Generated by Django 3.0.6 on 2020-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0008_survey_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='contacts',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
