# Generated by Django 3.0.6 on 2020-06-14 15:55

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0008_auto_20200614_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
