# Generated by Django 3.0.6 on 2020-06-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0009_answer_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Answer')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Question')),
                ('survey', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='polyresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='polyresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='polyresponse',
            name='survey',
        ),
        migrations.DeleteModel(
            name='MonoResponse',
        ),
        migrations.DeleteModel(
            name='PolyResponse',
        ),
    ]
