# Generated by Django 3.0.6 on 2020-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0009_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_text',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
