# Generated by Django 3.0.6 on 2020-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0009_survey_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='page',
            field=models.ManyToManyField(blank=True, to='surveys_app.Page'),
        ),
    ]
