# Generated by Django 3.0.6 on 2020-05-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0010_survey_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='respond_counter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
