# Generated by Django 3.0.6 on 2020-06-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0010_auto_20200614_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Предлагаемый вариант ответа', 'verbose_name_plural': 'Предлагаемые варианты ответов'},
        ),
    ]
