# Generated by Django 3.0.6 on 2020-05-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0011_auto_20200531_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=32, null=True)),
                ('page_text', models.TextField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='page_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.PageInfo'),
        ),
    ]
