# Generated by Django 3.0.6 on 2020-05-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0011_survey_respond_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Language'),
            preserve_default=False,
        ),
    ]
