# Generated by Django 3.0.6 on 2020-05-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0012_auto_20200531_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageInfo',
            new_name='InfoPage',
        ),
        migrations.RenameField(
            model_name='infopage',
            old_name='page_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='infopage',
            old_name='page_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_info',
            new_name='info',
        ),
    ]
