# Generated by Django 3.0.6 on 2020-06-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0012_auto_20200614_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnCode',
        ),
    ]
