# Generated by Django 3.0.6 on 2020-05-13 01:45

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0012_survey_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='surveys_app.Survey'),
        ),
    ]
