# Generated by Django 3.0.6 on 2020-05-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0013_survey_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='return_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
