# Generated by Django 3.0.6 on 2020-05-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0013_auto_20200531_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.InfoPage')),
            ],
        ),
        migrations.CreateModel(
            name='NumberPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ManyToManyField(blank=True, to='surveys_app.Question')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='survey',
            name='info_pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.InfoPages'),
        ),
        migrations.AddField(
            model_name='survey',
            name='pages',
            field=models.ManyToManyField(blank=True, to='surveys_app.NumberPages'),
        ),
    ]
