# Generated by Django 3.0.6 on 2020-05-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0014_survey_return_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='return_code',
        ),
    ]
