# Generated by Django 3.0.6 on 2020-05-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0015_auto_20200531_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopages',
            name='info',
        ),
        migrations.AddField(
            model_name='infopage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.InfoPages'),
        ),
    ]
