# Generated by Django 3.0.6 on 2020-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0016_auto_20200531_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoPages',
            new_name='NamedPages',
        ),
    ]
