# Generated by Django 3.0.6 on 2020-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0016_returncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returncode',
            name='return_code',
            field=models.CharField(max_length=8),
        ),
    ]
