# Generated by Django 3.0.6 on 2020-06-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0021_auto_20200601_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ManyToManyField(blank=True, to='surveys_app.Question')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='respond_counter',
            new_name='answers_counter',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='pages',
        ),
        migrations.AddField(
            model_name='survey',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NumberPages',
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
        migrations.AddField(
            model_name='pages',
            name='survey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
    ]
