# Generated by Django 3.0.6 on 2020-06-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0023_auto_20200602_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='draft',
            new_name='is_draft',
        ),
    ]
