# Generated by Django 3.0.6 on 2020-06-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0024_auto_20200602_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='language',
        ),
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.ManyToManyField(blank=True, default='1', to='surveys_app.Language'),
        ),
    ]
