# Generated by Django 3.0.6 on 2020-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0025_auto_20200602_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='total_pages',
            field=models.SmallIntegerField(default=0),
        ),
    ]
