# Generated by Django 3.0.6 on 2020-06-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0027_survey_has_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='page_number',
        ),
    ]
