# Generated by Django 3.0.6 on 2020-06-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0030_auto_20200607_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_help',
            field=models.TextField(blank=True, default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys_app.Survey'),
        ),
    ]
