# Generated by Django 3.0.6 on 2020-06-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0031_auto_20200607_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='number',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_help',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
