# Generated by Django 3.0.6 on 2020-06-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0032_auto_20200609_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
