# Generated by Django 3.0.6 on 2020-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0033_auto_20200609_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='question_type_name',
            field=models.CharField(max_length=16),
        ),
    ]
