# Generated by Django 3.0.6 on 2020-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0034_auto_20200609_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_help',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
