# Generated by Django 3.0.6 on 2020-06-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0035_auto_20200610_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='question_type_name',
            field=models.CharField(max_length=24),
        ),
    ]
