# Generated by Django 3.0.6 on 2020-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0003_remove_company_user'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, to='companies_app.Company'),
        ),
    ]
