# Generated by Django 3.0.6 on 2020-05-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='companies',
        ),
    ]
